#!/bin/bash
###################################
#   Server monitor + TG update 	  #
###################################
#   Created by Kirill Rudenko	  #
###################################

## variables

TOKEN=''   #your token goes here
APIURL='' #your API updates URL goes here
USR=$(whoami)
FILENAME='updates.json'
TIME=$(date '+%H:%M:%S')
MES1="ALERT! MySQL is DOWN at $TIME!"
MES2="ALERT! Apache is DOWN at $TIME!"
MES3="ALERT! VSFTPD is DOWN at $TIME!"


	if [ -f $FILENAME ]; then
		rm -rf $FILENAME
		wget $APIURL -O $FILENAME > /dev/null 2>&1
	else 
		wget $APIURL -O $FILENAME > /dev/null 2>&1
	fi

CHAT_ID=$(tail -n 1 $FILENAME |grep "chat" |grep "id" |grep "/start" |grep -Eo "[-0-9][-0-9][-0-9][-0-9][-0-9][-0-9][-0-9][-0-9][-0-9]" |sed -n '1p')

## main function

live_stat() {
		if [ -f top.txt ]; then
		rm -rf top.txt
		top -b -n 1 > top.txt
		else
		top -b -n 1 > top.txt
		fi

		if [ -f process.txt ]; then
		rm -rf process.txt
		ps aux |grep $USR |awk '{print $1 " " $3 " " $11}' |sort -hr |head -10 > process.txt
		else
		ps aux |grep $USR |awk '{print $1 " " $3 " " $11}' |sort -hr |head -10 > process.txt
		fi

	## MySQL is alive?

	if [ $(ps aux |grep -v grep |egrep '(mariadb|mysqld)' |wc -l) = 0 ]; then
			curl -s -X POST https://api.telegram.org/bot{$TOKEN}/sendMessage -d chat_id=$CHAT_ID -d text="$MES1" > /dev/null 2>&1
	fi

	## Apache is alive?

	if [ $(ps aux |grep -v grep |egrep '(httpd|apache)' |wc -l) = 0 ]; then
			curl -s -X POST https://api.telegram.org/bot{$TOKEN}/sendMessage -d chat_id=$CHAT_ID -d text="$MES2" > /dev/null 2>&1
	fi

	## VSFTPD is alive?

	if [ $(ps aux |grep -v grep |egrep '(ftpd|vsftpd)' |wc -l) = 0 ]; then
			curl -s -X POST https://api.telegram.org/bot{$TOKEN}/sendMessage -d chat_id=$CHAT_ID -d text="$MES3" > /dev/null 2>&1
	fi

	#CPU load high?
	CPU=$(top -bn2 | grep "Cpu(s)" |sed -n '2p' |awk '{print $2}' |sed 's/,/./g')
	MES4="ALERT! CPU load is CRITICAL! Current load - $CPU at $TIME!"
	if (( $(echo "$CPU > 75" |bc) )); then 
		curl -s -X POST https://api.telegram.org/bot{$TOKEN}/sendMessage -d chat_id=$CHAT_ID -d text="$MES4" > /dev/null 2>&1
		curl -s -X POST https://api.telegram.org/bot{$TOKEN}/sendDocument?chat_id=$CHAT_ID  -F document="@top.txt"  > /dev/null 2>&1; 
		curl -s -X POST https://api.telegram.org/bot{$TOKEN}/sendDocument?chat_id=$CHAT_ID  -F document="@process.txt" > /dev/null 2>&1; 

	
	fi

}

live_stat
