#!/bin/bash
###################################
#   Server monitor + TG update 	  #
###################################
#   Created by Kirill Rudenko	  #
###################################

#
#variables
#
TOKEN='648758527:AAEDP8DuUjYpKvfBuysTfIHsNDDLjZ58KBA' #your token goes here
APIURL='https://api.telegram.org/bot648758527:AAEDP8DuUjYpKvfBuysTfIHsNDDLjZ58KBA/getUpdates' #your API updates URL goes here
USR=$(whoami)
TIME=$(date '+%H:%M:%S')
RAM=$(free -mh |awk '{print $3}' |sed -n 2p)
RAMT=$(free -mh |grep Mem |awk '{print $2}')
SPACEU=$(du $HOME -sh |sort -n |uniq -c |awk '{print $2}')
SPACET=$(df $HOME -h |awk '{print $2}' |sed 's/Size//g;/^$/d;')
LOGINS=$(who | cut -d' ' -f1 | sort | uniq)
NETSTATG=$(netstat -tulpn |grep -c ESTABLISHED)
NETSTATDB=$(netstat -tulpn |grep -c 3306)
MES1='Hello'
MES2="Current time on the server - $TIME"
MES3="Currently logged users on the server are: $LOGINS"
MES4="Number of established connections to the server $NETSTATG"
MES5="Number of connections to the database $NETSTATDB"
MES6="Disc space used $SPACEU from $SPACET in total"
MES7="$RAM of RAM is used from $RAMT in total"
MES9="Here is the detailed top output"
MES10="Here are top 10 CPU consuming processes that are currently running"
##
##	main function
##

show_statistics() {
##
## last API call + TG user + ID 
##	
	FILENAME='updates.json'

	if [ -f $FILENAME ]; then
		rm -rf $FILENAME
		wget $APIURL -O $FILENAME > /dev/null 2>&1
	else 
		wget $APIURL -O $FILENAME > /dev/null 2>&1
	fi
	CHAT_ID=$(tail -n 1 $FILENAME |grep "chat" |grep "id" |grep "/start" |grep -Eo "[-0-9][-0-9][-0-9][-0-9][-0-9][-0-9][-0-9][-0-9][-0-9]" |sed -n '1p')
##
##
## sending the stats
##
##	
	
if [ -f top.txt ]; then
	rm -rf top.txt
	top -b -n 1 > top.txt
	else
	top -b -n 1 > top.txt
fi

if [ -f process.txt ]; then
	rm -rf process.txt
	ps aux |grep $USR |awk '{print $1 " " $3 " " $11}' |sort -hr |head -10 > process.txt
	else
	ps aux |grep $USR |awk '{print $1 " " $3 " " $11}' |sort -hr |head -10 > process.txt
fi
	
	curl -s -X POST https://api.telegram.org/bot{$TOKEN}/sendMessage -d chat_id=$CHAT_ID -d text="$MES1" > /dev/null 2>&1
	curl -s -X POST https://api.telegram.org/bot{$TOKEN}/sendMessage -d chat_id=$CHAT_ID -d text="$MES2" > /dev/null 2>&1
	curl -s -X POST https://api.telegram.org/bot{$TOKEN}/sendMessage -d chat_id=$CHAT_ID -d text="$MES3" > /dev/null 2>&1
	curl -s -X POST https://api.telegram.org/bot{$TOKEN}/sendMessage -d chat_id=$CHAT_ID -d text="$MES4" > /dev/null 2>&1
	curl -s -X POST https://api.telegram.org/bot{$TOKEN}/sendMessage -d chat_id=$CHAT_ID -d text="$MES5" > /dev/null 2>&1
	curl -s -X POST https://api.telegram.org/bot{$TOKEN}/sendMessage -d chat_id=$CHAT_ID -d text="$MES6" > /dev/null 2>&1
	curl -s -X POST https://api.telegram.org/bot{$TOKEN}/sendMessage -d chat_id=$CHAT_ID -d text="$MES7" > /dev/null 2>&1
	curl -s -X POST https://api.telegram.org/bot{$TOKEN}/sendMessage -d chat_id=$CHAT_ID -d text="$MES8" > /dev/null 2>&1
	curl -s -X POST https://api.telegram.org/bot{$TOKEN}/sendMessage -d chat_id=$CHAT_ID -d text="$MES9" > /dev/null 2>&1
	curl -s -X POST https://api.telegram.org/bot{$TOKEN}/sendDocument?chat_id=$CHAT_ID  -F document="@top.txt"  > /dev/null 2>&1; 
	curl -s -X POST https://api.telegram.org/bot{$TOKEN}/sendMessage -d chat_id=$CHAT_ID -d text="$MES10" > /dev/null 2>&1
	curl -s -X POST https://api.telegram.org/bot{$TOKEN}/sendDocument?chat_id=$CHAT_ID  -F document="@process.txt" > /dev/null 2>&1; 

	rm -rf top.txt
	rm -rf process.txt
}


show_statistics
