#!/bin/bash
###################################
#   Server monitor + TG update 	  #
###################################
#   Created by Kirill Rudenko	  #
###################################

#
#Linux distro check + required stuff install
#
if [ -d /usr/bin/mpstat ]; then
	echo "OK" > /dev/null 2>&1;
elif grep ^NAME /etc/*release | grep CentOS > /dev/null 2>&1; then
	DISTRO="CentOS"
	sudo yum install sysstat -y 
elif cat /etc/*release | grep ^NAME | grep Red > /dev/null 2>&1; then
	DISTRO="RedHat"
	sudo yum install sysstat -y 
elif cat /etc/*release | grep ^NAME | grep Fedora > /dev/null 2>&1; then
    DISTRO="Fedora"
    sudo yum install sysstat -y 
 elif cat /etc/*release | grep ^NAME | grep Ubuntu > /dev/null 2>&1; then
    DISTRO="Ubuntu"
    sudo apt install sysstat -y 
 elif cat /etc/*release | grep ^NAME | grep Debian > /dev/null 2>&1; then
 	DISTRO="Debian"
 	sudo apt install sysstat -y 
fi
#
#variables
#
TOKEN='648758527:AAEDP8DuUjYpKvfBuysTfIHsNDDLjZ58KBA' 
USR=$(whoami)
TIME=$(date '+%H:%M:%S')
CPUALL=$(mpstat -P ALL |awk '{print $3}' |sed -n 4p)
RAM=$(free -mh |awk '{print $3}' |sed -n 2p)
SPACEU=$(du $HOME -sh |sort -n |uniq -c |awk '{print $2}')
SPACET=$(df $HOME -h |awk '{print $2}' |sed 's/Size//g;/^$/d;')
LOGINS=$(who | cut -d' ' -f1 | sort | uniq)
NETSTATG=$(netstat -tulpn |grep -c ESTABLISHED)
NETSTATDB=$(netstat -tulpn |grep -c 3306)
MES1='Hello'
MES2="Current time on the server - $TIME"
MES3="Currently logged users on the server are: $LOGINS"
MES4="Number of established connections to the server $NETSTATG"
MES5="Number of connections to the database $NETSTATDB"
MES6="Disc space used $SPACEU from $SPACET in total"
MES7="$RAM of RAM is used"
MES8="Load on all CPU cores in total - $CPUALL"
MES9="Here is the detailed CPU cores load"
MES10="Here are top 10 CPU consuming processes that are currently running"
##
##	functions list 
##

show_statistics() {
##
## last API call + TG user + ID 
##	
	FILENAME='updates.json'

	if [ -f $FILENAME ]; then
		rm -rf $FILENAME
		wget https://api.telegram.org/bot648758527:AAEDP8DuUjYpKvfBuysTfIHsNDDLjZ58KBA/getUpdates -O $FILENAME > /dev/null 2>&1
	else 
		wget https://api.telegram.org/bot648758527:AAEDP8DuUjYpKvfBuysTfIHsNDDLjZ58KBA/getUpdates -O $FILENAME > /dev/null 2>&1
	fi
	CHAT_ID=$(tail -n 1 updates.json |grep "chat" |grep "id" |grep "/start" |grep -Eo "[-0-9][-0-9][-0-9][-0-9][-0-9][-0-9][-0-9][-0-9][-0-9]" |sed -n '1p')
##
##
## sending the stats
##
##	
	
if [ -f core_load.txt ]; then
	rm -rf core_load.txt
	mpstat -P ALL > core_load.txt
	else
	mpstat -P ALL > core_load.txt
fi

if [ -f process.txt ]; then
	rm -rf process.txt
	ps aux |grep $USR |awk '{print $1 " " $3 " " $11}' |sort -hr |head -10 > process.txt
	else
	ps aux |grep $USR |awk '{print $1 " " $3 " " $11}' |sort -hr |head -10 > process.txt
fi
	
	curl -s -X POST https://api.telegram.org/bot{$TOKEN}/sendMessage -d chat_id=$CHAT_ID -d text="$MES1" > /dev/null 2>&1
	curl -s -X POST https://api.telegram.org/bot{$TOKEN}/sendMessage -d chat_id=$CHAT_ID -d text="$MES2" > /dev/null 2>&1
	curl -s -X POST https://api.telegram.org/bot{$TOKEN}/sendMessage -d chat_id=$CHAT_ID -d text="$MES3" > /dev/null 2>&1
	curl -s -X POST https://api.telegram.org/bot{$TOKEN}/sendMessage -d chat_id=$CHAT_ID -d text="$MES4" > /dev/null 2>&1
	curl -s -X POST https://api.telegram.org/bot{$TOKEN}/sendMessage -d chat_id=$CHAT_ID -d text="$MES5" > /dev/null 2>&1
	curl -s -X POST https://api.telegram.org/bot{$TOKEN}/sendMessage -d chat_id=$CHAT_ID -d text="$MES6" > /dev/null 2>&1
	curl -s -X POST https://api.telegram.org/bot{$TOKEN}/sendMessage -d chat_id=$CHAT_ID -d text="$MES7" > /dev/null 2>&1
	curl -s -X POST https://api.telegram.org/bot{$TOKEN}/sendMessage -d chat_id=$CHAT_ID -d text="$MES8" > /dev/null 2>&1
	curl -s -X POST https://api.telegram.org/bot{$TOKEN}/sendMessage -d chat_id=$CHAT_ID -d text="$MES9" > /dev/null 2>&1
	curl -s -X POST https://api.telegram.org/bot{$TOKEN}/sendDocument?chat_id=$CHAT_ID  -F document="@core_load.txt"  > /dev/null 2>&1; 
	curl -s -X POST https://api.telegram.org/bot{$TOKEN}/sendMessage -d chat_id=$CHAT_ID -d text="$MES10" > /dev/null 2>&1
	curl -s -X POST https://api.telegram.org/bot{$TOKEN}/sendDocument?chat_id=$CHAT_ID  -F document="@process.txt" > /dev/null 2>&1; 

}


show_statistics
