#!/bin/bash
###################################
#   Server monitor + TG update 	  #
###################################
#   Created by Kirill Rudenko	  #
###################################

TOKEN='648758527:AAEDP8DuUjYpKvfBuysTfIHsNDDLjZ58KBA'
APIURL='https://api.telegram.org/bot648758527:AAEDP8DuUjYpKvfBuysTfIHsNDDLjZ58KBA/getUpdates' 
FILENAME='updates.json'
MES1='MySQL is DOWN!'
MES2='Apache is DOWN!'

	if [ -f $FILENAME ]; then
		rm -rf $FILENAME
		wget $APIURL -O $FILENAME > /dev/null 2>&1
	else 
		wget $APIURL -O $FILENAME > /dev/null 2>&1
	fi

CHAT_ID=$(tail -n 1 updates.json |grep "chat" |grep "id" |grep "/start" |grep -Eo "[-0-9][-0-9][-0-9][-0-9][-0-9][-0-9][-0-9][-0-9][-0-9]" |sed -n '1p')


f_alive() {

	## MySQL is alive?

	if (( $(ps aux |grep -v grep |egrep '(mariadb|mysqld)' |wc -l) = 0 )); then
			curl -s -X POST https://api.telegram.org/bot{$TOKEN}/sendMessage -d chat_id=$CHAT_ID -d text="$MES1" > /dev/null 2>&1
	fi

	## Apache is alive?

	if (( $(ps aux |grep -v grep |egrep '(httpd|apache)' |wc -l) = 0 )); then
			curl -s -X POST https://api.telegram.org/bot{$TOKEN}/sendMessage -d chat_id=$CHAT_ID -d text="$MES1" > /dev/null 2>&1
	fi
}

f_alive
